### ISSUE TITLE
Cannot make it to Step 3 on install

### ISSUE THREAD

**Issue by RonCowart** [kbrmedia/Premium-URL-Shortener#10]
Hi...

I downloaded the your most recent version of Premium-URL-Shortener yesterday and since I recently changed over to a new webhost (BlueHost), I thought it would be a perfect time for a new, fresh install, since I didn't migrate all of my old files from my previous host.

Everything has gone fine, until I click continue on the auto-install, to take me to step 3. Nothing happens. It's just a blank page and when I look at the source code, all I see is a "1."

I've started over a couple of times, thinking I inadvertently missed a step, however, with the easy-to-use install that you built-in, you simply can't miss a step.

This is my URL where I'm installing the script....

http://10n1.net

Thanks,
Ron

**Comment by kbrmedia** [comment]
@RonCowart Please use the latest installer.
