### ISSUE TITLE
Bug in newest update 10/09/2019

### ISSUE THREAD

**Issue by RonCowart** [kbrmedia/Premium-URL-Shortener#11]
I downloaded the update you provided today and after installing it, I was able to get the script to successfully install on my server.

Now, in the process of updating my settings where I want them, I get to the section of "plans" where I've run across another issue.

The script allows me to create a free, "starter" plan. However, I cannot create a second plan. I "experimented" a bit with it, attempting to save it at different intervals, so as to narrow down the issue but when I went to save it without a price, it correctly "notified" me that a price was required, since I had already used the free plan. 

When I place both the monthly and the yearly prices in and click save, again a white, text-less page appears. And again, looking at the source code, I see a "1."

Thanks.

Ron

http://10n1.net

**Comment by kbrmedia** [comment]
Hey @RonCowart 

Can you open a ticket at https://gemp.me/help?

**Comment by RonCowart** [comment]
Josh, I used the absolute latest installer you put up a couple of days ago and that worked! I have my site up and running and taking URL's.

http://10n1.net/

Thanks!

Ron

**Comment by kbrmedia** [comment]
Awesome :)
