### ISSUE TITLE
Data too long for column 'meta_title'

### ISSUE THREAD

**Issue by grandtele** [kbrmedia/Premium-URL-Shortener#12]
Hi,

problem url

https://ali.srl/r/89a05c1a427605a31de7ae4f4f4068e3?subid=1&dpl=https%3A%2F%2Fru.aliexpress.com%2Fitem%2F32818190373.html%3Fspm%3Da2g0o.ams_89724.p99adbb.11.793b269ajUlDFJ%26gps-id%3D5868181%26scm%3D1007.20675.119384.0%26scm_id%3D1007.20675.119384.0%26scm-url%3D1007.20675.119384.0%26pvid%3D0cb1b91a-461a-4ec1-bb93-006aec1a28f4

fix
ALTER TABLE `url` CHANGE `meta_title` `meta_title` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL;

**Comment by kbrmedia** [comment]
Hello. Thanks for the info. We will correct this :)
