### ISSUE TITLE
Upgraded from 5.6.5 to 5.7.2 and can no longer edit or add any new plans.

### ISSUE THREAD

**Issue by markthompson1** [kbrmedia/Premium-URL-Shortener#13]
I wanted to use the "CUSTOM ALIAS AS PREMIUM" feature but after upgrading from 5.6.5 to 5.7.2 at the weekend I could no longer edit or add any new plans.

I deleted the starter plan and tried adding it back to see if this would work but when I added starter back it complained that the plan already existed even though it had been deleted. I added it back as starter1 but it failed to add. 

I found this out as follows.

Workflow

1. Enable "custom alias" in the Bussiness plan
2. Click the blue "Edit plan" button at the bottom of the screen.
3. The screen clears and hangs indefinitely @ https://ado.red/admin/plans/edit/2.
4. If I put my cursor in the URL window and press enter I go back to the "Edit plan" screen but nothing has changed, Custom Alias is still off.
5. If I refresh the browser (ctrl/cmd R) I have to confirm form resubmission and then I get the following error highlighted in red. "Something went wrong please try again".

I then tried to change other features and I couldn't change or edit any of the plans as I get the same problem every time.

The result of deleting the starter plan meant I could no longer log in and so was forced to restore from a backup. My site is now back on 5.6.5, do I need and the "Edit plan" functionality is working again.

How do I upgrade to use the new features, do I have to install all the interim versions first, i.e. 5.7, 5.7.1 and then 5.7.2. 

I opened a support ticket at the weekend.

 - OS: MAC OSX 10.14.6 Mojave
 - Browser: Chrome
 - Version: 80.0.3987.100 (Official Build) (64-bit)

**Comment by kbrmedia** [comment]
Hey Mark. Did you run the file updater.php? In case grab the latest updater.php file from a fresh package on codecanyon, upload and run it. If you experience the same issue, go to file includes/config.php and set the debug value to 2 and let me know what the error says via the ticket.

**Comment by markthompson1** [comment]
Thanks, Josh, that is likely the problem. I will try the update again after my next weekly backup on Sunday.

 

Mark

**Comment by markthompson1** [comment]
Hi Josh,

 

I have just upgraded again, this time using the automated script and I still have the problem I reported on GitHub last week, i.e. I can’t add or edit any of the plans.

 

E.g.

 

I just tried to change the plan name from Business to Business+ and it failed in the same way I described on GitHub.

 

 

 

 

 

 

CMD+R

 

 

 

Mark

**Comment by markthompson1** [comment]
Hi Josh,

I have just upgraded again but this time using the automated script and I have exactly the same problem I reported here last week. I have sent you an email with more details and screenshots.

Mark

**Comment by markthompson1** [comment]
After manually uploading updater.php and updating the DB everything is now working as expected.

Sorry for the trouble, please close this bug report.

Thanks
