### ISSUE TITLE
Custom domain binding problem

### ISSUE THREAD

**Issue by askofcc** [kbrmedia/Premium-URL-Shortener#17]
On the dedicated server, after the user points through CNAME
The webmaster must add this domain name on the background server to take effect
Can't you remove the step that the administrator adds this domain name on the background server
My version is 5.7.2 dedicated server apache
Have read https://gempixel.com/docs/premium-url-shortener#cd

**Comment by kbrmedia** [comment]
Hello

We cannot remove that step as that is at the server level. If you enable 000-default.conf on your server and point that to the base script, all domains to your will be automatically work.
