### ISSUE TITLE
Error While Creating a Plan 

### ISSUE THREAD

**Issue by vijaykumarim** [kbrmedia/Premium-URL-Shortener#22]
**Describe the bug**
When I create a plan in the admin panel it first shows blank page then it starts showing the plan already exists. https://g-et.me/admin/plans

**To Reproduce**
1. Go to 'https://g-et.me/admin/plans/add'
2. After adding the details as in this screenshot https://imgur.com/jgJkaro
3. Then when I clicked on add button it is showing the error message like this https://prnt.sc/u5z2zw

**Expected behavior**
It should add the plan or show error like there are fields required to fill. Where as when I added first time it showed blank page after creating new plan since then it started showing already exists. 

**Verification**
I bought extended license but it seems very difficult set up with extremely bad support.

**Comment by kbrmedia** [comment]
Hello @vijaykumarim 

Please check the ticket. That error is not normal.
