### ISSUE TITLE
Stripe India Module is Not Working.

### ISSUE THREAD

**Issue by vijaykumarim** [kbrmedia/Premium-URL-Shortener#23]
**Describe the bug**
My Stripe account is in India. I am not able to make payment as it is showing number of errors. https://prnt.sc/u5zavg.

**To Reproduce**
1. Go to 'https://g-et.me/'
2. Click on 'Plan'
3. Try to make payment with Stripe test card details as I enabled Test mode
4. See error https://prnt.sc/u5zdph . Not showing any details here but in the stripe dashboard it shows everything https://prnt.sc/u5zavg

**Expected behavior**
A plan should be charged and should be able to make payment. 

**Screenshots**
https://prnt.sc/u5zavg
https://prnt.sc/u5zdph

**Comment by kbrmedia** [comment]
Hello @vijaykumarim 

Please see ticket and provide info so we can check this. Sometimes Stripe can act weird for India so we have to make special changes.
