### ISSUE TITLE
URL Redirection - 404 NOT FOUND

### ISSUE THREAD

**Issue by khalequzzaman17** [kbrmedia/Premium-URL-Shortener#29]
Hello,

Suppose, I've installed the script on https://domainname.tld/ and used the URL without www in the Admin panel » settings » Site URL. Well, now, after creating a shortened URL (example: https://domainname.tld/LztPt ), if I visit through the site URL it redirects to the destination URL. but, when I add www with the URL (example: https://www.domainname.tld/LztPt ), it doesn't. It shows an error. Screenshot: https://prnt.sc/z4t6iw.

Hope, you'll see the matter.

**Comment by khalequzzaman17** [comment]
Hi there! Did you fixed the issue?

**Comment by kbrmedia** [comment]
Hello

Please follow the instructions on this page https://gempixel.com/solutions/how-to-redirect-www-to-non-www-with-htaccess-on-your-site to redirect www to non-www version of your site. Only one of these should exist at a time.
