### ISSUE TITLE
The splash page is not showing preview of final site.

### ISSUE THREAD

**Issue by mustafahasankhan** [kbrmedia/Premium-URL-Shortener#35]
**Describe the bug**
Miniature.io (the site used by the script to show preview of webpages of final destination of shortened URLs) is broken, this is the reason preview of the final webpages is not available.

**To Reproduce**
1. Go to any splash shortened link
2. See the image (it will show a non available image)
3. See error

**Expected behavior**
Web preview of final destination website of the shortened link.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version Latest

**Comment by kbrmedia** [comment]
Hello

We are using third-party screenshot generator.
