### ISSUE TITLE
Need to improve SEO

### ISSUE THREAD

**Issue by hridoythebest5** [kbrmedia/Premium-URL-Shortener#37]
We are using this script for a long time and trying improve SEO score but we are unable to do this because of lack of seo option on this script. 
Please add more seo option in this script so that user can rank on any search engine more easily.

You can visit our website for more information and live preview
MatchURL - No. 1 URL Shortener
[removed] 
MatchURL one of the best Premium URL shortener in the world for affiliate marketers and agencies. It provides advanced tracking system, Realtime Clicks, Targeting Tools, Branded Domains, Redirection Types, Link Rotator, Tracking Pixels, Team Members, advanced analytical features. It also provides paid membership.
Best For : matchurl, urlshortener, shortener, pof shortener, meetme shortener, hi5 shortener, hily shortener, baidu shortener,

**Comment by kbrmedia** [comment]
Hello

The script already provides you the option to add description and keywords. You can also add your custom metatags by editing theme files directly.
