### ISSUE TITLE
WiFi and SMS QR codes not working

### ISSUE THREAD

**Issue by luisclarafernandes** [kbrmedia/Premium-URL-Shortener#40]
**Describe the bug**
QR codes generated to configure a wifi or send an SMS are not working on iPhones. When you scan it, the browser opens and nothing happens.

**To Reproduce**

1. Generate a SMS or WiFi QR code.
2. Scan it with the camera of an iPhone X or an Iphone 11.

**Expected behavior**
Open sms screen with the number and message pre-entered / Open Wifi configuration pre-entered. 

**Device**
- iPhone X
- iPhone 11

**Comment by kbrmedia** [comment]
Fixed in v6.1.9
