### ISSUE TITLE
App stopped working

### ISSUE THREAD

**Issue by lscherr** [kbrmedia/Premium-URL-Shortener#6]
The app stopped working.  Server was upgraded to php 5.6.  I upgraded the link shortner to the newest version 5.4.3.  Ran updater.   It looks good, all of my previous links are there and work however I can't add a new link (looks like it works and gives a short link but it goes to a 404 page and doesn't show in the list of links) and I can't add a new user (get blank screen).  Any clues what's going on?    thanks, Louis

**Comment by kbrmedia** [comment]
Hello Louis

We will need to check out what is going on. You can create a ticket at https://support.gempixel.com
