### ISSUE TITLE
url shorter

### ISSUE THREAD

**Issue by yasin-dogan38** [kbrmedia/Premium-URL-Shortener#8]
We got the Link shortening script, but it's shortclass.php is Php deleting its own file ?
Acil dönüş yaparmısınız roseyazilim@gmail.com

**Comment by kbrmedia** [comment]
Hello

The script is not deleting that file it is your server. Please get in touch from your host.

**Comment by yasin-dogan38** [comment]
I'm looking through the chorome that said the server is fine shortclass.can you see php deleting its own through TeamViewer?

**Comment by yasin-dogan38** [comment]
http://prntscr.com/oh0tla

shortclass.php none

**Comment by kbrmedia** [comment]
It might your server's antivirus. Tell them to check their anti virus.

**Comment by yasin-dogan38** [comment]
okay, thanks. I'm opening a ticket.
